import { NextResponse } from 'next/server';

const HTML = '<!DOCTYPE html>\n<html lang="ru">\n<head>\n  <meta charset="UTF-8"/>\n  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>\n  <meta name="apple-mobile-web-app-capable" content="yes"/>\n  <meta name="theme-color" content="#0A0C0F"/>\n  <title>GodLocal Voice</title>\n  <link rel="stylesheet" href="/static/pwa/voice.css">\n</head>\n<body>\n<div id="app">\n  <header>\n    <a class="logo" href="/">\n      <div class="li">G</div>\n      <span class="lt">God<span>Local</span> Voice</span>\n    </a>\n    <div class="hr">\n      <div id="dot" title="API status"></div>\n      <button id="sb-btn" onclick="openSettings()" aria-label="Settings">&#9881;</button>\n    </div>\n  </header>\n  <div id="chat">\n    <div id="empty">\n      <div class="ei">🎙️</div>\n      <p>Нажми кнопку и говори,<br/>или напечатай вопрос.</p>\n      <small>GodLocal AI · godlocal-api</small>\n    </div>\n  </div>\n  <div id="live"></div>\n  <div id="bot">\n    <div id="st">подключение…</div>\n    <div id="orb" role="button" aria-label="Speak"><span id="oi">⏳</span></div>\n    <div id="tr">\n      <input id="ti" type="text" placeholder="или напечатай здесь…" autocomplete="off" autocorrect="off" autocapitalize="off"/>\n      <button id="sb" onclick="sendText()">&#9658;</button>\n    </div>\n    <div id="acts">\n      <button class="act" id="mb" onclick="toggleMute()">🔊 звук</button>\n      <button class="act" onclick="clearChat()">🗑 очистить</button>\n    </div>\n  </div>\n  <div id="sp">\n    <div class="sph">\n      <span class="spt">⚙️ Настройки</span>\n      <button id="spc" onclick="closeSettings()">&#215;</button>\n    </div>\n    <div class="sg">\n      <label>Голос TTS</label>\n      <select id="vs" onchange="saveCfg()"></select>\n    </div>\n    <div class="sg">\n      <label>Скорость речи</label>\n      <input type="range" id="rs" min="0.6" max="1.6" step="0.1" value="1.0" oninput="saveCfg()"/>\n    </div>\n    <div class="sg">\n      <label>Персона</label>\n      <select id="ps" onchange="saveCfg()">\n        <option value="">GodLocal AI (умный агент)</option>\n        <option value="j">Jarvis — точный и быстрый</option>\n        <option value="s">Sage — вдумчивый и глубокий</option>\n        <option value="w">WOLF — прямой, без воды</option>\n      </select>\n    </div>\n    <div class="sg">\n      <label>Язык распознавания</label>\n      <select id="ls" onchange="saveCfg()">\n        <option value="ru-RU">Русский</option>\n        <option value="en-US">English</option>\n      </select>\n    </div>\n    <p class="sn">Оранжевая точка — сервер просыпается (15-30 сек при первом запросе). Зелёная — готово.</p>\n  </div>\n</div>\n<script src="/static/pwa/voice.js"></script>\n</body>\n</html>';

export async function GET() {
  return new NextResponse(HTML, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store, no-cache, must-revalidate',
    },
  });
}