name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Override git author for Vercel
        run: |
          git config user.email "provodnikx100@gmail.com"
          git config user.name "GodLocal"
          git commit --amend --reset-author --no-edit

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: prj_Z04A9gWialQ72Wqu9jKACrYWhdCK

      - name: Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: prj_Z04A9gWialQ72Wqu9jKACrYWhdCK

      - name: Deploy
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: prj_Z04A9gWialQ72Wqu9jKACrYWhdCK
